FROM "mireiawen/debian:latest"

SHELL [ "/bin/bash", "-e", "-u", "-o", "pipefail", "-c" ]
RUN echo -e "{{ LOCALES }}" >"/etc/locale.gen" && \
        /usr/sbin/locale-gen

RUN echo "{{ CONTAINER }}" >"/etc/system_name"

RUN useradd \
	--comment "{{ NAME }}" \
	--home-dir "/home/{{ USER }}" \
	--user-group \
	--groups "sudo,docker" \
	--create-home \
	--uid "{{ UID }}" \
	"{{ USER }}"

# hadolint ignore=DL3000
WORKDIR "/home/{{ USER }}"

ENV USERNAME="{{ USER }}"
ENTRYPOINT ["/docker-entrypoint.sh"]
