---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

name: "Docker Image CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '15 0 * * *'

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
    - name: "Checkout"
      uses: "actions/checkout@v2"
    - name: "Create the tag name"
      run: |
        export TAG="buster-$(date --utc '%Y.%m.%d')"
        echo "::set-env name=TAG::${TAG}"
    - name: "Build the Docker image"
      run: docker build "." --tag "mireiawen/debian:${{ env.TAG }}"
    - name: "Log in to the registry"
      run: docker login --username "${{secrets.DOCKERHUB_USERNAME}}" --password "${{secrets.DOCKERHUB_PASSWORD}}"
    - name: "Push the Docker image"
      run: docker push --tag "mireiawen/debian:${{ env.TAG }}"
